### ISSUE TITLE
Remove outdated link

### ISSUE THREAD

**Issue by ccamara** [WarwickCIM/IM939_handbook#11]
Readme file and index.qmd point to https://cagatayturkay.github.io/data-science-across-disciplines and should point to https://warwick.ac.uk/fac/cross_fac/cim/apply-to-study/cross-disciplinary-postgraduate-modules/im939-data-science-across-disciplines

**Comment by eshasadia** [comment]
Hi, I've reviewed the links you highlighted and changed to the right one, closing this issue now
